name: On Push
on:
  push:
    branches:
      - master
jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: ./.github/actions/config-test
  #       with:
  #         test: true
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - run: pip install frc-characterization
      - run: cat `which frc-characterization`
