name: On Push
on:
  push:
    branches:
      - master
jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/cjdenio/actions-test.git
          git pull
      - uses: ./.github/actions/write-time
      - run: |
          git status
          git commit --amend -am "Update time"
          git push --set-upstream origin master