name: On Push
on:
  push:
    branches:
      - master
jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - uses: cjdenio/contributor_list@master