name: On Push
on: push
jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: ./.github/actions/write-time
      - run: git status