name: On Push
on:
  push:
    branches:
      - master
jobs: 
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/config-test
        with:
          test:
            moo: baa
            test: yep